"""
Configuration Module
"""

from .cities import MAJOR_CITIES, TEST_CITIES, REGIONS, HIGH_DEMAND_MARKETS
from .settings import (
    SCRAPER_CONFIG,
    ACTIVE_SCRAPERS,
    ANTHROPIC_API_KEY,
    USE_AI_PARSING,
    DATABASE_URL,
    EMAIL_CONFIG,
    EXPORT_CONFIG,
    SCHEDULE_CONFIG,
    PAY_CONVERSION,
    SPECIALTIES,
    JOB_TYPES,
)

__all__ = [
    'MAJOR_CITIES',
    'TEST_CITIES',
    'REGIONS',
    'HIGH_DEMAND_MARKETS',
    'SCRAPER_CONFIG',
    'ACTIVE_SCRAPERS',
    'ANTHROPIC_API_KEY',
    'USE_AI_PARSING',
    'DATABASE_URL',
    'EMAIL_CONFIG',
    'EXPORT_CONFIG',
    'SCHEDULE_CONFIG',
    'PAY_CONVERSION',
    'SPECIALTIES',
    'JOB_TYPES',
]
